blur_camera_app := blur_camera_app
SDK_PATH ?= C:/path/to/flipperzero-firmware
FIRMWARE_PATH ?= C:/FlipperZeroProjects/flipperzero-firmware

include $(SDK_PATH)/config.mk
include $(SDK_PATH)/rules.mk
$(eval $(call generate_app,$(blur_camera_app_Camera),main.c))
