APP_NAME := blur_camera_app
SDK_PATH ?= C:/path/to/flipperzero-firmware
FIRMWARE_PATH ?= C:/FlipperZeroProjects/flipperzero-firmware

include C:\Users\Soofree45\flipperzero-firmware-3\config.mkk
include $(SDK_PATH)/rules.mk
$(eval $(call generate_app,$(APP_NAME),main.c))
