APP_NAME := blur_camera_app
SDK_PATH ?= C:/path/to/flipperzero-firmware
FIRMWARE_PATH ?= C:/FlipperZeroProjects/flipperzero-firmware

include $(SDK_PATH)/config.mk
include $(SDK_PATH)/rules.mk
$(eval $(call generate_app,$(APP_NAME),main.c))
