#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <blur_camera_app_icons.h>

int32_t blur_camera_app_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm blur_camera_app!");

    return 0;
}
